### ISSUE TITLE
环境装好了， 运行出现这个错误

### ISSUE THREAD

**Issue by cy-dream** [spencer404/PyLoom#3]
Traceback (most recent call last):
  File "/usr/local/bin/pyloom", line 9, in <module>
    load_entry_point('pyloom', 'console_scripts', 'pyloom')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/PyLoom/pyloom/__init__.py", line 1, in <module>
    from .tasks import Task
  File "/root/PyLoom/pyloom/tasks.py", line 119
    raise `errors.TaskError(f"不支持从'{type(root)}'类型构造CSS")

**Comment by speng4096** [comment]
Python版本是什么呢？

**Comment by speng4096** [comment]
这种问题一般是Python版本小于3.6.0造成的，少了f-strings。
