### ISSUE TITLE
爬虫跑不起来

### ISSUE THREAD

**Issue by lochakho** [spencer404/PyLoom#7]
```
C:\Users\PC>pyloom run -s G:\PyLoom\spiders\WeiBo
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\Scripts\pyloom-script.py", line 11, in <module>
    load_entry_point('pyloom', 'console_scripts', 'pyloom')()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\pc\pyloom\pyloom\__init__.py", line 1, in <module>
    from .tasks import Task
  File "c:\users\pc\pyloom\pyloom\tasks.py", line 8, in <module>
    from .utils import *
  File "c:\users\pc\pyloom\pyloom\utils.py", line 9, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

请问者跑不起来

**Comment by speng4096** [comment]
缺少readline模块, 用 `pip3 install readline` 命令安装
